Poke filter component redesign
PokemonGoers/Catch-em-all pull request #109
Opened 2016-10-11 01:45 UTC by philbu

Some minor fixes and redesign of the pokemon filter tab of our popover.

I played a little bit with the design and made it more compact.
Tell me how you like it 
@PokemonGoers/catch-em-all 

![selection_002](https://cloud.githubusercontent.com/assets/21012888/19256160/99514512-8f64-11e6-97a7-12d33b31c4d9.png)
![selection_003](https://cloud.githubusercontent.com/assets/21012888/19256167/a8455cde-8f64-11e6-9394-2431eb266172.png)
![selection_004](https://cloud.githubusercontent.com/assets/21012888/19256198/dc42a866-8f64-11e6-86c3-b15f74b962e5.png)
![selection_005](https://cloud.githubusercontent.com/assets/21012888/19256204/e496bc96-8f64-11e6-883f-e2ab84b864df.png)

2016-10-11 08:47 UTC, goldbergtatyana commented
I like everything about it. Other opionions?

2016-10-11 10:37 UTC, AlexanderLill requested changes
I like the design very much :)

2016-10-11 10:37 UTC, AlexanderLill commented on ionic2/app/components/poke-filter-pokemon-tab/poke-filter-pokemon-tab.component.scss
> +}
An empty line in between wouldn't hurt :)

2016-10-11 10:37 UTC, AlexanderLill commented on ionic2/app/services/poke-types.ts
>  export const TYPES : { [key:string]:string; } = {
Sorting those seems unnecessary to me, but okay

2016-10-11 10:37 UTC, AlexanderLill commented on ionic2/app/components/poke-filter-pokemon-tab/poke-filter-pokemon-tab.component.ts
>      for (let str in this.apiservice.getTypes()) {
While you are at it anyway: Can you rename the `apiservice` to `apiService`? :)

2016-10-11 11:04 UTC, philbu commented on ionic2/app/components/poke-filter-pokemon-tab/poke-filter-pokemon-tab.component.scss
> +}
Between the elements or at the begin of the document?

2016-10-11 11:05 UTC, philbu commented on ionic2/app/services/poke-types.ts
>  export const TYPES : { [key:string]:string; } = {
It's not. Your pokemon-filter is displaying the types without sorting them

2016-10-11 11:07 UTC, philbu commented on ionic2/app/components/poke-filter-pokemon-tab/poke-filter-pokemon-tab.component.ts
>      for (let str in this.apiservice.getTypes()) {
Will be done in the next commit :)

2016-10-11 13:53 UTC, philbu commented
@AlexanderLill can you approve my changes?

2016-10-11 15:11 UTC, MajorBreakfast commented
I like the design. Good work. We should merge this ASAP.

The behavior of the pokemon filter needs some adjustment. Checking the boxes never does what I expect. The intended behavior is specified in https://github.com/PokemonGoers/Catch-em-all/issues/74 I can work on that as soon as this is merged

2016-10-11 15:16 UTC, merged

2016-10-11 16:42 UTC, WoH commented
@philbu Did you maybe forget something? :laughing:

2016-10-13 09:14 UTC, MajorBreakfast commented
That's why I always use my own repo. It currently has 8 branches and no one cares.

2016-10-17 11:56 UTC, johartl commented
@philbu Can this branch be deleted?

2016-10-17 12:11 UTC, MajorBreakfast commented
@johartl Polite way for saying "You forgot to delete the branch!" :)

2016-10-17 12:12 UTC, johartl commented
Always trying to be polite ;)