ionic RC1
PokemonGoers/Catch-em-all pull request #133
Opened 2016-10-19 20:45 UTC by WoH

See: https://github.com/PokemonGoers/Catch-em-all/issues/90

2016-10-19 22:19 UTC, AlexanderLill commented
Wow, that is ... a *lot*.

@sacdallago and @gyachdav should get their seminar statistics right - before you basically remove all our code ... ;)

Will review this tomorrow, wanna do this in one go before falling asleep...

2016-10-19 22:22 UTC, WoH commented
I left everything in tact whenever. I moved a lot of the stuff from /app... to /src, but I also had to scope the styles differently and as soon as that happens, github doesn't count it as moving a -> b but as removing a and adding b.

2016-10-20 07:28 UTC, MajorBreakfast commented
First: Good work! But...

![3875822](https://cloud.githubusercontent.com/assets/340142/19549748/60ac4196-96a6-11e6-9ccd-986e3429a01e.jpg)

We're loosing scoped styles?

2016-10-21 03:02 UTC, sacdallago commented
Hey guys will this PR fix the `ERROR NativeStorageError`? It's like super annoying!

I guess that's why the map is not loading? Maybe it also has to do with maxing out the requests at mapbox.

Just please merge if this is fine and fixes issues, we are like super late on schedule.

2016-10-21 09:41 UTC, WoH commented
@sacdallago thanks for reminding me of that. However, this is not related to RC1 and this PR is already not the smallest. I opened another one that tackles that issue. Once that PR is merged and #136 is solved, the map will load and load without errors.

2016-10-21 14:06 UTC, AlexanderLill requested changes
Looks good to me :)

2016-10-21 14:06 UTC, AlexanderLill commented on .travis.yml
> +  # - npm test
I guess this is removed because we do not have any tests?

2016-10-21 14:06 UTC, AlexanderLill approved these changes

2016-10-21 16:19 UTC, WoH commented on .travis.yml
> +  # - npm test
Exactly

2016-10-22 14:26 UTC, sacdallago commented
Can this finally be merged?

2016-10-23 08:51 UTC, WoH commented
Waiting for @johartl to confirm or add his thoughts.

2016-10-23 09:44 UTC, johartl commented
I will have a look today. Sorry for the delay.

2016-10-23 11:17 UTC, WoH commented
You need both I think, I was just about to fix that :D

2016-10-23 11:36 UTC, WoH commented
@johartl Is this good to go? I re-enabled everything that I had to work around and I think this is good to go now.

2016-10-23 12:11 UTC, johartl commented
Please give me some more time. Currently the Docker build is not working and I also want to test the Android build before merging it.

2016-10-23 12:14 UTC, WoH commented
@sacdallago is coming after us, I agree we shouldn't make any overzealous moves though.

2016-10-23 13:52 UTC, sacdallago commented
@WoH you bet I am

2016-10-23 14:02 UTC, johartl commented
@sacdallago I'm sure the last thing you want is a broken Docker build though ;)
From my side this PR is good to go now!

2016-10-23 14:03 UTC, johartl approved these changes

2016-10-23 14:11 UTC, sacdallago commented
@johartl oh, well, you know how to make a man happy, don't you?

2016-10-23 14:12 UTC, WoH commented
![KappaPride](https://static-cdn.jtvnw.net/emoticons/v1/55338/3.0)

I will merge as soon as I can conform that it integrates nicely with PM-1

2016-10-23 14:55 UTC, merged

2016-10-24 04:37 UTC, sacdallago commented
oh wow, this happened