Pokemondetail
PokemonGoers/Catch-em-all pull request #66
Opened 2016-09-18 21:41 UTC by AlexanderLill

Merge the branch with the pokemondetail-page (not entirely finished, but ready enough for showing it to others) into develop.

2016-09-19 16:18 UTC, WoH commented on ionic2/app/components/poke-details/poke-evolutions.component.ts
> +    for (var i=0, len=this.pokemon.nextEvolutions.length; i<len; i++) {
for(evolution of ....)

2016-09-19 16:20 UTC, WoH commented on ionic2/app/models/pokemon.ts
> -  previousEvolutions: [{
previousEvolution: Evolution[] or Evolution

2016-09-19 16:20 UTC, WoH commented on ionic2/app/models/pokemon.ts
> -  nextEvolutions: [{
See above

2016-09-19 16:24 UTC, WoH commented on ionic2/app/pages/poke-detail/poke-detail.page.ts
> +    this.apiservice.getPokemonById(this.pokemonId).subscribe(results => this.pokemon = results, error => this.pokemon = null);
?????

2016-09-19 16:25 UTC, WoH commented on ionic2/app/pages/poke-detail/poke-detail.page.ts
> -import {forwardRef} from "@angular/core";
Please pull the Pokemon off navParams, don't do another API call.

2016-09-19 16:25 UTC, WoH requested changes

2016-09-19 17:04 UTC, johartl commented on ionic2/app/components/poke-details/poke-stats.component.ts
> +  @Input("pokemon") pokemon: Pokemon;
Please use single quotes for consistency.

2016-09-19 17:06 UTC, johartl commented on ionic2/app/components/poke-details/poke-type.component.ts
> +  styles: [`
I know it's now a lot but I think it's more consistent to move the CSS to a different file rather than inlining it.

2016-09-19 17:07 UTC, johartl commented on ionic2/app/components/poke-details/poke-type.component.ts
> +      this.typeArray.push({element:item, color:color[item+'']})
What's the reason for using `item+''` here?

2016-09-19 17:08 UTC, johartl commented on ionic2/app/components/poke-details/poke-type.component.ts
> +  constructor() {
If we don't need the constructor just remove it :)

2016-09-19 17:10 UTC, johartl commented on ionic2/app/pages/poke-detail/poke-detail.page.ts
>  import { Pokemon } from "../../models/pokemon";
Again, would you be able to use single quotes here?

2016-09-19 17:11 UTC, johartl commented on ionic2/app/components/poke-details/poke-stats.component.ts
>    constructor() {}
Can you remove this constructor please?

2016-09-19 17:16 UTC, johartl commented on ionic2/app/components/poke-details/poke-type.component.ts
> +      this.typeArray.push({element:item, color:color[item+'']})
What's the reason for using `item+''` here?

2016-09-19 17:17 UTC, johartl commented on ionic2/app/pages/poke-detail/poke-detail.page.ts
> +import { forwardRef } from "@angular/core";
Do you mind using single quotes throughout the file?

2016-09-19 17:18 UTC, johartl commented on ionic2/app/components/poke-details/poke-type.component.ts
> +  styles: [`
I know it's not a lot of CSS but I think it would still be nice to move it to a separate file rather than inlining it.

2016-09-19 17:19 UTC, johartl commented on ionic2/app/components/poke-details/poke-stats.component.ts
> +import { Pokemon } from "../../models/pokemon";
Can we use single quotes here? Also for the `@Input("pokemon")` statement below.

2016-09-19 17:20 UTC, johartl commented on ionic2/app/components/poke-details/poke-evolutions.component.ts
> +import { Pokemon } from "../../models/pokemon";
Can we use single quotes here?

2016-09-19 17:25 UTC, johartl requested changes

2016-09-19 17:39 UTC, AlexanderLill commented on ionic2/app/models/pokemon.ts
> -  previousEvolutions: [{
done

2016-09-19 17:39 UTC, AlexanderLill commented on ionic2/app/models/pokemon.ts
> -  nextEvolutions: [{
done

2016-09-19 17:42 UTC, AlexanderLill commented on ionic2/app/pages/poke-detail/poke-detail.page.ts
> -import {forwardRef} from "@angular/core";
How exactly?
Isn't the poke-detail-page called only with the Id?

`this.navCtrl.push(PokeDetailPage, {pokemonId: pokemon.pokemonId});`

2016-09-19 17:59 UTC, AlexanderLill commented on ionic2/app/components/poke-details/poke-evolutions.component.ts
> +    for (var i=0, len=this.pokemon.nextEvolutions.length; i<len; i++) {
done

2016-09-19 17:59 UTC, AlexanderLill commented on ionic2/app/pages/poke-detail/poke-detail.page.ts
> -import {forwardRef} from "@angular/core";
done, works :)

2016-09-19 17:59 UTC, AlexanderLill commented on ionic2/app/pages/poke-detail/poke-detail.page.ts
> +    this.apiservice.getPokemonById(this.pokemonId).subscribe(results => this.pokemon = results, error => this.pokemon = null);
done, we push the whole pokemon now

2016-09-19 18:00 UTC, AlexanderLill commented on ionic2/app/components/poke-details/poke-type.component.ts
> +  styles: [`
mustafa will solve this in his next commit for the attacks styling

2016-09-19 18:00 UTC, AlexanderLill commented on ionic2/app/pages/poke-detail/poke-detail.page.ts
> +import { forwardRef } from "@angular/core";
replaced ALL of them :)

2016-09-19 18:00 UTC, AlexanderLill commented on ionic2/app/components/poke-details/poke-stats.component.ts
> +import { Pokemon } from "../../models/pokemon";
done

2016-09-19 18:02 UTC, AlexanderLill commented on ionic2/app/components/poke-details/poke-type.component.ts
> +      this.typeArray.push({element:item, color:color[item+'']})
Phil says there is no reason, it will be removed.

2016-09-19 18:03 UTC, AlexanderLill commented on ionic2/app/components/poke-details/poke-evolutions.component.ts
> +import { Pokemon } from "../../models/pokemon";
catched themall

2016-09-19 18:51 UTC, WoH approved these changes

2016-09-19 18:56 UTC, WoH commented on ionic2/app/components/poke-details/poke-attacks.component.ts
> +  @Input('pokemon') pokemon: Pokemon;
If you don't rename you can omit the selector:
@Input() pokemon: Pokemon;

2016-09-19 18:59 UTC, WoH commented on ionic2/app/components/poke-details/poke-evolutions.component.ts
> +  public prevPokemon: Pokemon;
Since the model defines Evolution[] as prev Pokemon it would be consistent to make this Pokemon[]

2016-09-19 19:01 UTC, WoH commented on ionic2/app/components/poke-details/poke-evolutions.component.ts
> +export class PokeEvolutionsComponent {
Angular 2 Styleguide would ask you to import and implement the OnInit interface if you use ngOnInit

2016-09-19 19:03 UTC, WoH commented on ionic2/app/components/poke-details/poke-type.component.ts
> +    const color={
It would be nice if we could move this out of the component

2016-09-20 08:07 UTC, johartl approved these changes

2016-09-20 11:58 UTC, AlexanderLill commented on ionic2/app/components/poke-details/poke-attacks.component.ts
> +  @Input('pokemon') pokemon: Pokemon;
done

2016-09-20 12:03 UTC, AlexanderLill commented on ionic2/app/components/poke-details/poke-evolutions.component.ts
> +export class PokeEvolutionsComponent {
done

2016-09-20 12:07 UTC, AlexanderLill commented on ionic2/app/components/poke-details/poke-evolutions.component.ts
> +  public prevPokemon: Pokemon;
done

2016-09-20 13:32 UTC, merged