PokeDex and PokeDex Detail pages changed/fixed
PokemonGoers/Catch-em-all pull request #81
Opened 2016-09-22 19:05 UTC by philbu

- Minor fixes in the css of PokeDex Detail
- Fixed loading issue in PokeDex

2016-09-22 21:23 UTC, WoH commented on ionic2/app/pages/poke-detail/poke-detail.page.scss
>  }
We should add a light grey background color (as in the Poke(in)Dex)

2016-09-22 21:24 UTC, WoH commented on ionic2/app/pages/wiki-index/wiki-index.page.ts
> +  ionViewDidEnter() {
I found viewLoaded to be better. Also, I fixed that in my fix all the things PR

2016-09-23 13:24 UTC, WoH commented
If you solve the merge conflict and keep my new hook intact this should be good to go.

2016-09-23 21:44 UTC, Lugitan commented
![badges_test_v2](https://cloud.githubusercontent.com/assets/12813614/18802052/db5d39b0-81e6-11e6-8215-544ce99dcd67.JPG)

I did a bit of styling and fixed the badges in the Pokémon details view. I created two options for the badges. First one is done with the `<ion-badge>` tag as before. For the second one the tag has been removed and will be just a `<div>` then.
Any Preferences?

2016-09-23 22:25 UTC, WoH commented
2/3 with the badge color corresponding to the the label color

2016-09-24 14:18 UTC, johartl commented
I like the div better. However, can you make the width of the badge a few pixels smaller.

2016-09-24 14:32 UTC, Lugitan commented
Sure. The dimensions are a bit weird anyway. I will look into it this evening.

2016-09-25 09:27 UTC, philbu commented on ionic2/app/pages/poke-detail/poke-detail.page.scss
>  }
Done

2016-09-25 09:29 UTC, philbu commented on ionic2/app/pages/wiki-index/wiki-index.page.ts
> +  ionViewDidEnter() {
Is your change already live? Didn't display a merge conflict with ionViewDidEnter

2016-09-25 09:34 UTC, philbu commented
Fixed the new image sources. It isn't .icon anymore. Instead it is .gifIcon, .pngIcon and .svgIcon. Unfortunately the data team hasn't uploaded pictures for svgIcon yet and the pngIcons aren't highres right now.

2016-09-26 09:33 UTC, AlexanderLill commented on ionic2/app/models/pokemon.ts
> +  get scgIcon(): string {
@philbu here is a typo :)

- [ ] rename "scg" -> "svg"

2016-09-26 09:36 UTC, AlexanderLill commented on ionic2/app/pages/wiki-index/wiki-index.page.ts
>    ionViewDidEnter() {
Do we have a use case where this query string might be pre-filled? Are we doing this when we jump back from the detail view?

2016-09-26 09:39 UTC, AlexanderLill requested changes

2016-09-26 10:00 UTC, philbu commented on ionic2/app/models/pokemon.ts
> +  get scgIcon(): string {
Thanks. Fixed it. :+1:

2016-09-26 10:46 UTC, AlexanderLill approved these changes

2016-09-28 11:54 UTC, johartl commented
Is this good to merge?

2016-09-29 18:52 UTC, johartl commented
@philbu I will merge this now. I really need some of the changes in here to finish the POI card.

2016-09-29 18:52 UTC, merged